version: 2
jobs:
  # publish jobs require $DOCKER_REPO, $DOCKER_USER, $DOCKER_PASS defined
  publish:
    docker:
        - image: circleci/python:3.6.8
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            LATEST_TAG=${CIRCLE_TAG:1} #trim v from tag
            #
            docker build --pull -t $DOCKER_REPO:$LATEST_TAG .
            docker login --username=$DOCKER_USER --password=$DOCKER_PASS
            docker push $DOCKER_REPO:$LATEST_TAG
workflows:
  version: 2

  publish:
    jobs:
      - publish:
          filters:
            # ignore any commit on any branch by default
            branches:
              ignore: /.*/
            # only act on version tags
            tags:
              only: /v(.)*/